#!/bin/bash

echo "🚀 UrbanDev Dashboard - Servidor de Teste"
echo "=========================================="
echo ""
echo "✅ Status: SERVIDOR RODANDO"
echo "📡 Porta: 3001"
echo "🌐 URL Principal: http://localhost:3001"
echo ""
echo "📊 APIs Disponíveis:"
echo "   • Estatísticas: http://localhost:3001/api/v1/dashboard/stats"
echo "   • Atividades:   http://localhost:3001/api/v1/dashboard/activity/recent"
echo "   • Analytics:    http://localhost:3001/api/v1/dashboard/analytics"
echo ""
echo "🔗 Links Diretos:"
echo "   • Dashboard: http://localhost:3001"
echo "   • API Stats: http://localhost:3001/api/v1/dashboard/stats"
echo "   • API Activity: http://localhost:3001/api/v1/dashboard/activity/recent"
echo "   • API Analytics: http://localhost:3001/api/v1/dashboard/analytics"
echo ""
echo "📋 Exemplo de Uso:"
echo "   curl http://localhost:3001/api/v1/dashboard/stats"
echo ""
echo "⚠️  Nota: Este é um servidor de teste com dados simulados."
echo "   A implementação completa está no diretório principal."
echo ""
echo "🛑 Para parar o servidor:"
echo "   pkill -f 'node test-server.js'"
echo ""